multi: fix input pkscript construction, add round trip spend test
lightninglabs/taro pull request #172
Opened 2022-10-17 21:55 UTC by jharveyb

Spun off of #159.

Fixes multiple issues that caused round-trip (minter->receiver->minter) spends to fail:

1. The input TaroCommitment tree was being mutated when computing new TaroCommitments.
2. The input TaroCommitment tree includes asset leaves with SplitCommitments populated, which does not match the tree used for the actual transfer TX.

For the receiver to spend back to the minter, they need to recompute the pkScript used in the anchor output. Both of these issues caused the pkScript to be computed incorrectly in `inputAnchorPkScript()`. The mismatched pkScript caused transaction broadcast to fail.

The new itest includes a round-trip spend to test this fix.

2022-10-18 03:34 UTC, Roasbeef requested changes
Superb debugging to pinpoint this issue! 

Few minor comments, but the diff reads well. This is one of those things we need to make sure is properly spelled out in the spec.

2022-10-18 03:34 UTC, Roasbeef commented on itest/addrs_test.go
> +		t.t, t, t.lndHarness.BackendCfg, t.lndHarness.Bob, t.universeServer,
👍

2022-10-18 03:34 UTC, Roasbeef commented on itest/addrs_test.go
> +func sendProof(t *harnessTest, src, dst *tarodHarness, rpcAddr *tarorpc.Addr,
👍 

Eventually I think we can pass a wrapper around this in as a `proof.Courier`, which'll help us test the various proof transfer options.

2022-10-18 03:34 UTC, Roasbeef commented on taroscript/send.go
> -	txTemplate := wire.NewMsgTx(int32(maxOutputIndex))
Ahh yeh this should be a version 2 tx, nice catch.

2022-10-18 03:34 UTC, Roasbeef commented on tarofreighter/parcel.go
> +
Style nit: extra new line here.

2022-10-18 03:34 UTC, Roasbeef commented on tarofreighter/parcel.go
> +	if len(inputAssetCopy.PrevWitnesses) == 1 &&
I think we can use `HasSplitCommitmentWitness` here.

2022-10-18 03:34 UTC, Roasbeef commented on tarofreighter/parcel.go
> +		inputAssetTree := inputAnchorCommitmentCopy.
I think we can use an intermediate variable here (or two) to get slightly prettier line wrapping?

2022-10-18 03:34 UTC, Roasbeef commented on itest/round_trip_send_test.go
> +// testFullValueSplitSend tests that we can properly send the full value of a
Should be `testRoundTripSend`

2022-10-18 03:34 UTC, Roasbeef commented on itest/round_trip_send_test.go
> +	sendProof(t, t.tarod, secondTarod, bobAddr, genInfo)
Perhaps we can wrap this and the mine+send above into a helper func? We'd then use the exact same func below when we send the assets back.

2022-10-18 03:34 UTC, Roasbeef commented on itest/round_trip_send_test.go
> +		require.Equal(t.t, delta.NewAmt, aliceAmt)
Can lift this into a helper assert func, params here are the amt, and the node to issue the query against. Same for the balances call.

2022-10-20 01:01 UTC, Roasbeef approved these changes
LGTM 🩴

2022-10-20 14:01 UTC, guggero approved these changes
Nice fixes and test enhancements, LGTM :tada: 

Just needs a rebase!

2022-10-20 16:07 UTC, jharveyb commented
Rebased!

2022-10-20 16:15 UTC, merged